# Generated by Django 5.0.1 on 2024-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_remove_team_upcoming_matches"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="player",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
